name: Docker Image CI

on:
  push:
    branches: [ "master", "no_mirror" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    
    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}
    
    - name: Build the Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./docker
        file: docker/rel4.dockerfile
        tags: ghcr.io/croakexciting/rel4_dev:${{ github.ref_name }}
        push: true